# Build debug APK and upload as artifact (includes Android SDK setup)
name: Build APK

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Android SDK (install platform & build-tools)
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 33
          arch: x86_64
          target: default
          # this action installs SDK, build-tools and accepts licenses

      - name: Make gradlew executable (if present)
        run: |
          if [ -f "./gradlew" ]; then
            chmod +x ./gradlew
          fi

      - name: Build Debug APK (prefer wrapper, fallback to system gradle)
        run: |
          if [ -f "./gradlew" ]; then
            ./gradlew assembleDebug --no-daemon
          else
            sudo apt-get update
            sudo apt-get install -y gradle
            gradle assembleDebug --no-daemon
          fi
        env:
          ANDROID_HOME: ${{ env.ANDROID_SDK_ROOT }}
          ANDROID_SDK_ROOT: ${{ env.ANDROID_SDK_ROOT }}

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: widgetpager-apk
          path: app/build/outputs/apk/debug/app-debug.apk
